---@class boss_chaos_fall: eom_ability
boss_chaos_fall = eom_ability({}, nil, ability_base_ai)
function boss_chaos_fall:OnSpellStart()
	local hCaster = self:GetCaster()
	local vPosition = self:GetCursorPosition()
	local damage = self:GetSpecialValueFor("damage")
	local radius = self:GetSpecialValueFor("radius")
	hCaster:EmitSound("Hero_Invoker.ChaosMeteor.Loop")
	local iParticleID = ParticleManager:CreateParticle("particles/units/heroes/hero_invoker/invoker_chaos_meteor_fly.vpcf", PATTACH_CUSTOMORIGIN, nil)
	ParticleManager:SetParticleControl(iParticleID, 0, hCaster:GetAbsOrigin() + Vector(0, 0, 1000))
	ParticleManager:SetParticleControl(iParticleID, 1, vPosition)
	ParticleManager:SetParticleControl(iParticleID, 2, Vector(1.3, 0, 0))
	ParticleManager:ReleaseParticleIndex(iParticleID)
	hCaster:GameTimer(1.3, function()
		local iParticleID = ParticleManager:CreateParticle("particles/units/heroes/hero_warlock/warlock_rain_of_chaos_start.vpcf", PATTACH_CUSTOMORIGIN, nil)
		ParticleManager:SetParticleControl(iParticleID, 0, vPosition)
		ParticleManager:SetParticleControl(iParticleID, 1, vPosition)
		ParticleManager:SetParticleControl(iParticleID, 2, vPosition)
		hCaster:EmitSound("Hero_Warlock.RainOfChaos_buildup")
		hCaster:StopSound("Hero_Invoker.ChaosMeteor.Loop")
	end)
	hCaster:GameTimer(1.5, function()
		local iParticleID = ParticleManager:CreateParticle("particles/units/heroes/hero_warlock/warlock_rain_of_chaos.vpcf", PATTACH_CUSTOMORIGIN, nil)
		ParticleManager:SetParticleControl(iParticleID, 0, vPosition)
		ParticleManager:SetParticleControl(iParticleID, 1, vPosition)
		ParticleManager:SetParticleControl(iParticleID, 2, vPosition)
		ParticleManager:SetParticleControl(iParticleID, 5, vPosition)
		hCaster:EmitSound("Hero_Warlock.RainOfChaos")
		hCaster:EmitSound("Hero_Invoker.ChaosMeteor.Impact")
		local tTargets = FindUnitsInRadiusWithAbility(hCaster, vPosition, radius, self)
		hCaster:DealDamage(tTargets, self, damage, DAMAGE_TYPE_MAGICAL)
		---@param hUnit CDOTA_BaseNPC
		for _, hUnit in ipairs(tTargets) do
			hUnit:AddNewModifier(hCaster, self, BUILT_IN_MODIFIER.STUNNED, { duration = 1 })
		end
	end)
end