"KeyValue"
{
	"item_clarity1"
	{
		"Note"									"小净化药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_clarity"
		"Model"									"models/props_gameplay/clarity.vmdl"
		"AbilityTextureName"					"item_clarity1"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"50"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_mana"					"150"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_per_tick"					"15"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_clarity2"
	{
		"Note"									"中净化药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_clarity"
		"Model"									"models/props_gameplay/clarity.vmdl"
		"AbilityTextureName"					"item_clarity2"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"150"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_mana"					"300"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_per_tick"					"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_clarity3"
	{
		"Note"									"大净化药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_clarity"
		"Model"									"models/props_gameplay/clarity.vmdl"
		"AbilityTextureName"					"item_clarity3"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"300"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_mana"					"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_per_tick"					"80"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_clarity4"
	{
		"Note"									"超净化药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_clarity"
		"Model"									"models/props_gameplay/clarity.vmdl"
		"AbilityTextureName"					"item_clarity4"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"800"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_mana"					"2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_per_tick"					"200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_salve1"
	{
		"Note"									"小回复药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_salve"
		"Model"									"models/props_gameplay/salve_red.vmdl"
		"AbilityTextureName"					"item_salve1"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"50"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_hp"						"600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"hp_per_tick"					"60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_salve2"
	{
		"Note"									"中回复药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_salve"
		"Model"									"models/props_gameplay/salve_red.vmdl"
		"AbilityTextureName"					"item_salve2"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"150"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_hp"						"1500"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"hp_per_tick"					"150"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_salve3"
	{
		"Note"									"大回复药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_salve"
		"Model"									"models/props_gameplay/salve_red.vmdl"
		"AbilityTextureName"					"item_salve3"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"300"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_hp"						"3000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"hp_per_tick"					"300"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_salve4"
	{
		"Note"									"超回复药水"
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_salve"
		"Model"									"models/props_gameplay/salve_red.vmdl"
		"AbilityTextureName"					"item_salve4"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"800"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"total_hp"						"6000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"hp_per_tick"					"600"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"buff_duration"					"10"
			}
		}
	}
	"item_salve1_pack"
	{
		"Note"									"小回复药水包"
		"BaseClass"								"item_datadriven"
		"Model"									"models/props_gameplay/salve_red.vmdl"
		"AbilityTextureName"					"item_salve1_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"2000"
		"ItemPermanent"							"0"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"count"							"50"
			}
		}
	}
	"item_clarity1_pack"
	{
		"Note"									"小净化药水包"
		"BaseClass"								"item_datadriven"
		"Model"									"models/props_gameplay/salve_red.vmdl"
		"AbilityTextureName"					"item_clarity1_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"2000"
		"ItemPermanent"							"0"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"count"							"50"
			}
		}
	}
	"item_str_book"
	{
		"Note"									"力量之书"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_str_book"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"10000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"10"
				"type"							"CUSTOM_ATTRIBUTE_STRENGTH"
			}
		}
	}
	"item_agi_book"
	{
		"Note"									"虚幻之书"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_agi_book"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"10000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"10"
				"type"							"CUSTOM_ATTRIBUTE_AGILITY"
			}
		}
	}
	"item_int_book"
	{
		"Note"									"魔力之书"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_int_book"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"10000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"10"
				"type"							"CUSTOM_ATTRIBUTE_INTELLECT"
			}
		}
	}
	"item_str_book_pack"
	{
		"Note"									"力量之书捆绑包"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_str_book_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"95000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"100"
				"type"							"CUSTOM_ATTRIBUTE_STRENGTH"
			}
		}
	}
	"item_agi_book_pack"
	{
		"Note"									"虚幻之书捆绑包"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_agi_book_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"95000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"100"
				"type"							"CUSTOM_ATTRIBUTE_AGILITY"
			}
		}
	}
	"item_int_book_pack"
	{
		"Note"									"魔力之书捆绑包"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_int_book_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"95000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"100"
				"type"							"CUSTOM_ATTRIBUTE_INTELLECT"
			}
		}
	}
	"item_str_book_pack_100"
	{
		"Note"									"力量之书超大捆绑包"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_str_book_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"900000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"1000"
				"type"							"CUSTOM_ATTRIBUTE_STRENGTH"
			}
		}
	}
	"item_agi_book_pack_100"
	{
		"Note"									"虚幻之书超大捆绑包"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_agi_book_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"900000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"1000"
				"type"							"CUSTOM_ATTRIBUTE_AGILITY"
			}
		}
	}
	"item_int_book_pack_100"
	{
		"Note"									"魔力之书超大捆绑包"
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_int_book_pack"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK"
		"ItemQuality"							"consumable"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"ItemCost"								"900000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"value"							"1000"
				"type"							"CUSTOM_ATTRIBUTE_INTELLECT"
			}
		}
	}
	"item_jian_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_1"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"1500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"80"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"200"
			}
		}
	}
	"item_jian_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_2"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"4500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"160"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"300"
			}
		}
	}
	"item_jian_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_3"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"10500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"15"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"320"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"400"
			}
		}
	}
	"item_jian_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_4"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"22500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"640"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"80"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"500"
			}
		}
	}
	"item_jian_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_5"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"46500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1280"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"160"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"600"
			}
		}
	}
	"item_jian_6"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_6"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"35"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1920"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"240"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"800"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"4800"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"2400"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"40"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"18"
			}
		}
	}
	"item_jian_7"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_7"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"2560"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"320"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"1000"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"6400"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"3200"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"50"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"20"
			}
		}
	}
	"item_jian_8"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_8"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"65"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"3840"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"480"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"1200"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"8000"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4000"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"60"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"22"
			}
		}
	}
	"item_jian_9"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jian"
		"AbilityTextureName"					"item_jian_9"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"80"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"5120"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"640"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_damage"				"1600"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"9600"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4800"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"70"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"25"
			}
		}
	}
	"item_fazhang_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_1"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"1500"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"20"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"8"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
		}
	}
	"item_fazhang_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_2"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"4500"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"80"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"25"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"16"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
		}
	}
	"item_fazhang_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_3"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"10500"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"15"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"160"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"30"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"32"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
		}
	}
	"item_fazhang_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_4"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"22500"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"320"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"35"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"64"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
		}
	}
	"item_fazhang_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_5"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"46500"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"640"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"80"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"128"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
		}
	}
	"item_fazhang_6"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_6"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"35"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"960"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"160"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"45"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"192"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"4800"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"2400"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"40"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"18"
			}
		}
	}
	"item_fazhang_7"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_7"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1280"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"240"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"50"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"256"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"6400"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"3200"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"50"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"20"
			}
		}
	}
	"item_fazhang_8"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_8"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"65"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1920"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"320"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"55"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"384"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"8000"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4000"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"60"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"22"
			}
		}
	}
	"item_fazhang_9"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_fazhang"
		"AbilityTextureName"					"item_fazhang_9"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"80"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"2560"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_intellect"				"480"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"ignore_armor_pct"				"60"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_int"							"512"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"9600"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4800"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"70"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"25"
			}
		}
	}
	"item_gong_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_1"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"1500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"item_physical_damage"			"2.5"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"item_magical_damage"			"2.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"100"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"10"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"2"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
		}
	}
	"item_gong_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_2"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"4500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"20"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"3"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
		}
	}
	"item_gong_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_3"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"10500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"item_physical_damage"			"7.5"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"item_magical_damage"			"7.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"400"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"4"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
		}
	}
	"item_gong_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_4"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"22500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"800"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"80"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"5"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
		}
	}
	"item_gong_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_5"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"46500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"item_physical_damage"			"12.5"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"item_magical_damage"			"12.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1600"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"160"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"6"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
		}
	}
	"item_gong_6"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_6"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"item_physical_damage"			"17.5"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"item_magical_damage"			"17.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"2400"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"240"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"8"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"4800"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"2400"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"40"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"18"
			}
		}
	}
	"item_gong_7"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_7"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"25"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"3200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"320"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"10"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"6400"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"3200"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"50"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"20"
			}
		}
	}
	"item_gong_8"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_8"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"item_physical_damage"			"32.5"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"item_magical_damage"			"32.5"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"4800"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"480"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"12"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"8000"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4000"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"60"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"22"
			}
		}
	}
	"item_gong_9"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_gong"
		"AbilityTextureName"					"item_gong_9"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_MAIN_WEAPON"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_physical_damage"			"40"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_damage"			"40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"6400"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_agility"					"640"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"split_count"					"14"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_attack_damage"				"1"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"9600"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4800"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"70"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"125"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"25"
			}
		}
	}
	"item_jia_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jia"
		"AbilityTextureName"					"item_jia_1"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARMOR"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"1000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"5"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"30"
			}
		}
	}
	"item_jia_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jia"
		"AbilityTextureName"					"item_jia_2"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARMOR"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"400"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"60"
			}
		}
	}
	"item_jia_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jia"
		"AbilityTextureName"					"item_jia_3"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARMOR"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"15"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"90"
			}
		}
	}
	"item_jia_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jia"
		"AbilityTextureName"					"item_jia_4"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARMOR"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"1600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"80"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"120"
			}
		}
	}
	"item_jia_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_jia"
		"AbilityTextureName"					"item_jia_5"
		"ItemType"								"weapon"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARMOR"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"100"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"30"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"150"
			}
		}
	}
	"item_xie_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_xie"
		"AbilityTextureName"					"item_xie_1"
		"ItemType"								"weapon"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"1000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"3"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"100"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"4"
			}
		}
	}
	"item_xie_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_xie"
		"AbilityTextureName"					"item_xie_2"
		"ItemType"								"weapon"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"40"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"6"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"8"
			}
		}
	}
	"item_xie_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_xie"
		"AbilityTextureName"					"item_xie_3"
		"ItemType"								"weapon"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"60"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"9"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"400"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"12"
			}
		}
	}
	"item_xie_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_xie"
		"AbilityTextureName"					"item_xie_4"
		"ItemType"								"weapon"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"80"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"12"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"800"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"16"
			}
		}
	}
	"item_xie_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/weapon/item_xie"
		"AbilityTextureName"					"item_xie_5"
		"ItemType"								"weapon"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed"			"100"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"15"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1600"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"20"
			}
		}
	}
	"item_enchant_critical"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_enchant_critical"
		"AbilityTextureName"					"item_enchant"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ENCHANT"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"4000"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_chance"				"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_mutiple"				"40"
			}
		}
	}
	"item_enchant_reduce_armor"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_enchant_reduce_armor"
		"AbilityTextureName"					"item_enchant"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ENCHANT"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"4000"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce"						"6"
			}
		}
	}
	"item_enchant_reduce_resistance"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_enchant_reduce_resistance"
		"AbilityTextureName"					"item_enchant"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ENCHANT"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"4000"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_FLOAT"
				"reduce"						"2.5"
			}
		}
	}
	"item_enchant_lifesteal"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_enchant_lifesteal"
		"AbilityTextureName"					"item_enchant"
		"ItemType"								"consumable"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ENCHANT"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET | DOTA_ABILITY_BEHAVIOR_DONT_RESUME_ATTACK"
		"ItemCost"								"4000"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"100"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"lifesteal"						"4"
			}
		}
	}
	"item_shipin_1"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_1"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"5000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"2000"
			}
		}
	}
	"item_shipin_2"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_2"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"4000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"100"
			}
		}
	}
	"item_shipin_3"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_3"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"2500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"40"
			}
		}
	}
	"item_shipin_4"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_4"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"2500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"10"
			}
		}
	}
	"item_shipin_5"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_5"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"1000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1000"
			}
		}
	}
	"item_shipin_6"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_6"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"43500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1000"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"10"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"100"
			}
		}
	}
	"item_shipin_7"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"shipin_7"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"43500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_shipin_8"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_talisman_of_evasion"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"3000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"20"
			}
		}
	}
	"item_shipin_9"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_hood_of_defiance"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"4000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"10"
			}
		}
	}
	"item_shipin_10"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_stout_shield"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"300"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_physical"	"10"
			}
		}
	}
	"item_shipin_11"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_wind_lace"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"3500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_movement_speed_pct"		"10"
			}
		}
	}
	"item_shipin_12"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_helm_of_iron_will"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"5000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"12"
			}
		}
	}
	"item_shipin_13"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_blades_of_attack"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"1200"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"60"
			}
		}
	}
	"item_dragonhawk_cloak"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_dragonhawk_cloak"
		"AbilityTextureName"					"item_dragonhawk_cloak"
		"ItemQuality"							"common"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"5000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_miss"					"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_movespeed"				"-15"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"500"
			}
		}
	}
	"item_dragonhawk_cloak_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_dragonhawk_cloak"
		"AbilityTextureName"					"item_dragonhawk_cloak_2"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"5000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_miss"					"30"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"12"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_movespeed"				"-25"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
		}
	}
	"item_dragonhawk_cloak_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_dragonhawk_cloak"
		"AbilityTextureName"					"item_dragonhawk_cloak_3"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"5000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_miss"					"35"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"14"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_movespeed"				"-35"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"700"
			}
		}
	}
	"item_dragonhawk_cloak_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_dragonhawk_cloak"
		"AbilityTextureName"					"item_dragonhawk_cloak_4"
		"ItemQuality"							"artifact"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"5000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_miss"					"40"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"16"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_movespeed"				"-50"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
		}
	}
	"item_sun_emblem"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_sun_emblem"
		"AbilityTextureName"					"item_sun_emblem"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"1"
		"AbilityCooldown"						"16"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_armor"					"-15"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"80"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"20"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"10"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"5"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"375"
			}
		}
	}
	"item_sun_emblem_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_sun_emblem"
		"AbilityTextureName"					"item_sun_emblem_2"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"2"
		"AbilityCooldown"						"16"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_armor"					"-30"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"15"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"12"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"120"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"40"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"375"
			}
		}
	}
	"item_sun_emblem_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_sun_emblem"
		"AbilityTextureName"					"item_sun_emblem_3"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"3"
		"AbilityCooldown"						"16"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_armor"					"-45"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"14"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"160"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"20"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"7"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"375"
			}
		}
	}
	"item_sun_emblem_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_sun_emblem"
		"AbilityTextureName"					"item_sun_emblem_4"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"4"
		"AbilityCooldown"						"16"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_armor"					"-60"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"25"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"16"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"240"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"100"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"25"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"8"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"375"
			}
		}
	}
	"item_prestige_pipe"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_prestige_pipe"
		"AbilityTextureName"					"item_pipe"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"1"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"20"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"miss"							"40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"325"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"20"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"health_regen_pct"				"2"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"aura_radius"					"900"
			}
		}
	}
	"item_prestige_pipe_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_prestige_pipe"
		"AbilityTextureName"					"item_pipe_2"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"2"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"20"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"100"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"miss"							"50"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"325"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"30"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"health_regen_pct"				"4"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"aura_radius"					"900"
			}
		}
	}
	"item_prestige_pipe_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_prestige_pipe"
		"AbilityTextureName"					"item_pipe_3"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"3"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"20"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"4000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"140"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"30"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"miss"							"60"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"325"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"40"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"health_regen_pct"				"6"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"aura_radius"					"900"
			}
		}
	}
	"item_prestige_pipe_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_prestige_pipe"
		"AbilityTextureName"					"item_pipe_4"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_AOE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"MaxUpgradeLevel"						"4"
		"ItemBaseLevel"							"4"
		"AbilityCastRange"						"1200"
		"AbilityCooldown"						"20"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"5000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"180"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"miss"							"70"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"325"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"6"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"50"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"health_regen_pct"				"8"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"aura_radius"					"900"
			}
		}
	}
	"item_poor_man_shield"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_poor_mans_shield"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"15"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"5"
			}
		}
	}
	"item_buckler_shield"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_buckler"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"30"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"15"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"25"
			}
		}
	}
	"item_vanguard_shield"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_vanguard_shield"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"60"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
		}
	}
	"item_vanguard_shield_2"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_vanguard_shield_2"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"120"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"25"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"25"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"6000"
			}
		}
	}
	"item_vanguard_shield_3"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_vanguard_shield_3"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"240"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"30"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"9000"
			}
		}
	}
	"item_vanguard_shield_4"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_vanguard_shield_4"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"480"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"35"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_evasion"					"35"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"12000"
			}
		}
	}
	"item_urn_of_shadow"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_urn_of_shadow"
		"AbilityTextureName"					"item_urn_of_shadows"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_AUTOCAST"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemSellable"							"0"
		"ItemStackable"							"1"
		"AbilityCastRange"						"900"
		"AbilityManaCost"						"150"
		"AbilityCooldown"						"16"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_percent"				"10"
			}
			"02"
			{
				"var_type"						"FIELD_FLOAT"
				"damage_per_soul"				"0.1"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"50"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1200"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"max_soul"						"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"attribute_per_soul"			"5"
			}
		}
	}
	"item_spirit_vessel_capture"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_spirit_vessel_capture"
		"AbilityTextureName"					"item_spirit_vessel"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemSellable"							"0"
		"ItemPurchasable"						"0"
		"ItemStackable"							"1"
		"AbilityCastRange"						"900"
		"AbilityManaCost"						"150"
		"AbilityCooldown"						"16"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_percent"				"20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"300"
			}
		}
	}
	"item_spirit_vessel_release"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_spirit_vessel_release"
		"AbilityTextureName"					"item_spirit_vessel"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemSellable"							"0"
		"ItemPurchasable"						"0"
		"ItemStackable"							"1"
		"AbilityCastRange"						"900"
		"AbilityManaCost"						"150"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"120"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"300"
			}
		}
	}
	"item_demon_chains"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/accessory/item_demon_chains"
		"AbilityTextureName"					"item_nullifier"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_UNIT_TARGET | DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemPurchasable"						"0"
		"AbilityCastRange"						"1000"
		"AbilityManaCost"						"300"
		"AbilityCooldown"						"30"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"300"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"4000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"attribute_per_soul"			"5"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"30"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"reduce_armor"					"-80"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"08"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.2"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"respawn_time"					"30"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"attack"						"0"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"armor"							"0"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"health"						"0"
			}
			"13"
			{
				"var_type"						"FIELD_INTEGER"
				"str"							"0"
			}
			"14"
			{
				"var_type"						"FIELD_INTEGER"
				"agi"							"0"
			}
			"15"
			{
				"var_type"						"FIELD_INTEGER"
				"int"							"0"
			}
		}
	}
	"item_zhanqi"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/quest/item_zhanqi"
		"AbilityTextureName"					"item_zhanqi"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"100"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack"					"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_speed"			"50"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
		}
	}
	"item_xiongpi"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_xiongpi"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"100"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"80"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"20"
			}
		}
	}
	"item_hexin"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_hexin"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"100"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"2500"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1800"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"2"
			}
		}
	}
	"item_zhangu"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/quest/item_zhangu"
		"AbilityTextureName"					"item_zhangu"
		"ItemQuality"							"rare"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_FRIENDLY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"2000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"1"
		"ItemCastOnPickup"						"0"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"20"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3500"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"2800"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_ignore_damage"			"80"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"heal_amount"					"20"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"mana_amount"					"8"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_lifesteal"				"10"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack"					"25"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_attack_speed"			"50"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
		}
	}
	"item_craft_dun"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_craft_dun"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"10000"
		"ItemSellable"							"1"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_craft_fu"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_craft_fu"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"10000"
		"ItemSellable"							"1"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_craft_chui"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_craft_chui"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"10000"
		"ItemSellable"							"1"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_craft_shu"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_craft_shu"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"10000"
		"ItemSellable"							"1"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_baoshi_1"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_baoshi_1"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"1000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_baoshi_2"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_baoshi_2"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"2000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_baoshi_3"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_baoshi_3"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"3000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_baoshi_4"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_baoshi_4"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"4000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_baoshi_5"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_baoshi_5"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"5000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_blood_mask_broken"
	{
		"BaseClass"								"item_datadriven"
		"Model"									"models/props_gameplay/red_box.vmdl"
		"Effect"								"particles/generic_gameplay/dropped_item.vpcf"
		"AbilityTextureName"					"item_blood_mask_broken"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"lifesteal"						"10"
			}
		}
	}
	"item_blood_mask"
	{
		"BaseClass"								"item_datadriven"
		"Model"									"models/props_gameplay/red_box.vmdl"
		"Effect"								"particles/generic_gameplay/dropped_item.vpcf"
		"AbilityTextureName"					"item_blood_mask"
		"ItemQuality"							"epic"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemPurchasable"						"0"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"lifesteal"						"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed"					"50"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed"						"50"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"12"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"attackspeed_stack"				"15"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"lifesteal_stack"				"1"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"movespeed_stack"				"20"
			}
		}
	}
	"item_yunshizhaohuan"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/quest/item_yunshizhaohuan"
		"Model"									"models/props_gameplay/cheese.mdl"
		"Effect"								"particles/generic_gameplay/dropped_item.vpcf"
		"AbilityTextureName"					"item_chaos_demon"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"80"
		"ItemPurchasable"						"0"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"700"
		"AbilityManaCost"						"200"
		"AbilityCooldown"						"55"
	}
	"item_blink1"
	{
		"BaseClass"								"item_datadriven"
		"Model"									"models/props_gameplay/red_box.vmdl"
		"Effect"								"particles/generic_gameplay/dropped_item.vpcf"
		"AbilityTextureName"					"item_blink1"
		"ItemQuality"							"component"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT | DOTA_ABILITY_BEHAVIOR_ROOT_DISABLES"
		"ItemCost"								"22250"
		"ItemPurchasable"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"10"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"blink_range"					"5000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"min_blink_range"				"200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"bonus_damage"					"2000"
			}
		}
	}
	"item_firecracker"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_firecrackers"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"ItemCost"								"1000"
		"ItemPurchasable"						"0"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"200"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"50"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"200"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
			"04"
			{
				"var_type"						"FIELD_FLOAT"
				"interval"						"0.1"
			}
			"05"
			{
				"var_type"						"FIELD_FLOAT"
				"delay"							"2.5"
			}
		}
	}
	"item_firecracker_big"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_firework_mine"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"ItemCost"								"5000"
		"ItemPurchasable"						"0"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"200"
	}
	"item_butianshi"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_butianshi"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"40000"
		"ItemSellable"							"0"
		"ItemPurchasable"						"0"
		"ItemStackable"							"0"
		"ItemCastOnPickup"						"0"
		"AbilityCastRange"						"0"
		"AbilityManaCost"						"0"
		"AbilityCooldown"						"0"
	}
	"item_summon_dummy"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_summon_dummy"
		"AbilityTextureName"					"item_courier_dire"
		"ItemType"								"consumable"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_POINT"
		"ItemCost"								"10000"
		"ItemSellable"							"1"
		"ItemPurchasable"						"1"
		"ItemPermanent"							"0"
		"ItemStackable"							"1"
		"ItemInitialCharges"					"1"
		"AbilityCastRange"						"1000"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"20"
			}
		}
	}
	"item_fu_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_fu"
		"AbilityTextureName"					"item_fu_1"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_damage"			"70"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_radius"			"200"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_chance"				"15"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_percent"				"25"
			}
		}
	}
	"item_fu_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_fu"
		"AbilityTextureName"					"item_fu_2"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"400"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_damage"			"140"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_radius"			"280"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"80"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_chance"				"15"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_percent"				"30"
			}
		}
	}
	"item_fu_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_fu"
		"AbilityTextureName"					"item_fu_3"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_damage"			"210"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_radius"			"340"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"160"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_chance"				"15"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_percent"				"35"
			}
		}
	}
	"item_fu_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_fu"
		"AbilityTextureName"					"item_fu_4"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_damage"			"280"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_radius"			"420"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"320"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_chance"				"15"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_percent"				"40"
			}
		}
	}
	"item_fu_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_fu"
		"AbilityTextureName"					"item_fu_5"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityCooldown"						"60"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_damage"			"350"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cleave_radius"			"500"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_chance"				"15"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"waist_cut_percent"				"50"
			}
		}
	}
	"item_dun_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_dun"
		"AbilityTextureName"					"item_dun_1"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce"			"5"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"15"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"40"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"5000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_dun_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_dun"
		"AbilityTextureName"					"item_dun_2"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce"			"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"80"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"8000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_dun_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_dun"
		"AbilityTextureName"					"item_dun_3"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce"			"15"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"45"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"160"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"12000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_dun_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_dun"
		"AbilityTextureName"					"item_dun_4"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce"			"20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"60"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"320"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"17000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_dun_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_dun"
		"AbilityTextureName"					"item_dun_5"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityCooldown"						"60"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce"			"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_armor"					"75"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"500"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"25000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
		}
	}
	"item_shu_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_shu"
		"AbilityTextureName"					"item_shu_1"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cooldown_reduction"		"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"2000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"20"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_shu_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_shu"
		"AbilityTextureName"					"item_shu_2"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cooldown_reduction"		"15"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"80"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"3000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"30"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_shu_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_shu"
		"AbilityTextureName"					"item_shu_3"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cooldown_reduction"		"20"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"160"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"4500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"45"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_shu_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_shu"
		"AbilityTextureName"					"item_shu_4"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cooldown_reduction"		"25"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"320"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"6500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"65"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
		}
	}
	"item_shu_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_shu"
		"AbilityTextureName"					"item_shu_5"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityCooldown"						"60"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cooldown_reduction"		"30"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"500"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"9000"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"90"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"10"
			}
		}
	}
	"item_chui_1"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_chui"
		"AbilityTextureName"					"item_chui_1"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"400"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"40"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"300"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"10"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_chance"					"15"
			}
			"11"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"0.6"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_cooldown"					"2"
			}
		}
	}
	"item_chui_2"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_chui"
		"AbilityTextureName"					"item_chui_2"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"80"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"350"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"20"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_chance"					"20"
			}
			"11"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"0.8"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_cooldown"					"2"
			}
		}
	}
	"item_chui_3"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_chui"
		"AbilityTextureName"					"item_chui_3"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1200"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"160"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"400"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"30"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_chance"					"25"
			}
			"11"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_duration"					"1"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_cooldown"					"2"
			}
		}
	}
	"item_chui_4"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_chui"
		"AbilityTextureName"					"item_chui_4"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"1600"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"320"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"450"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"40"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_chance"					"30"
			}
			"11"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"1.2"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_cooldown"					"2"
			}
		}
	}
	"item_chui_5"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/deputy/item_chui"
		"AbilityTextureName"					"item_chui_5"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_DEPUTY"
		"ItemQuality"							"epic"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"AbilityCooldown"						"60"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"2000"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"500"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"3000"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"1500"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health_regen"				"60"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen"				"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"150"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"500"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"50"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_chance"					"35"
			}
			"11"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"1.4"
			}
			"12"
			{
				"var_type"						"FIELD_INTEGER"
				"stun_cooldown"					"2"
			}
		}
	}
	"item_chaos_plate"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/artifact/item_chaos_plate"
		"AbilityTextureName"					"item_aeon_disk"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARTIFACT"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"CrystalCost"							"20000"
		"ItemSellable"							"1"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
		"AbilityCooldown"						"90"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_health"					"20000"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce"			"25"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"shield"						"30"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"respawn_time"					"1"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"avoid_duration"				"5"
			}
		}
	}
	"item_world_editor"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/artifact/item_world_editor"
		"AbilityTextureName"					"item_world_editor"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARTIFACT"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"CrystalCost"							"20000"
		"ItemSellable"							"1"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
		"AbilityCooldown"						"90"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"health"						"10"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"regen"							"10"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"30"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_outgoing_damage"			"50"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"800"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"600"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_reduce"					"25"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"health_bonus"					"60000"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"block"							"10"
			}
		}
	}
	"item_longinus_spear"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/artifact/item_longinus_spear"
		"AbilityTextureName"					"item_longinus_spear"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARTIFACT"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"AbilityUnitDamageType"					"DAMAGE_TYPE_MAGICAL"
		"CrystalCost"							"20000"
		"ItemSellable"							"1"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
		"AbilityCastRange"						"600"
		"AbilityCooldown"						"90"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_percent"				"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"block_percent"					"20"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"item_outgoing_damage"			"40"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"400"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"trigger_percent"				"10"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana"						"60000"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen_pct"			"15"
			}
			"09"
			{
				"var_type"						"FIELD_FLOAT"
				"stun_duration"					"2.25"
			}
		}
	}
	"item_mystletainn"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/artifact/item_mystletainn"
		"AbilityTextureName"					"item_mystletainn"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARTIFACT"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"CrystalCost"							"20000"
		"ItemSellable"							"1"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"1"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"500"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_damage"			"4444"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"critical"						"100"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"absorb"						"2"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"attack_increase"				"44"
			}
			"07"
			{
				"var_type"						"FIELD_FLOAT"
				"item_attack_rate"				"-0.5"
			}
			"08"
			{
				"var_type"						"FIELD_INTEGER"
				"critical_rate"					"10"
			}
			"09"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"1"
			}
			"10"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_deepen"					"100"
			}
		}
	}
	"item_yata_mirror"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/artifact/item_yata_mirror"
		"AbilityTextureName"					"item_yata_mirror"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARTIFACT"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"CrystalCost"							"20000"
		"ItemSellable"							"1"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
		"AbilityCooldown"						"15"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_damage_reduce_magical"	"30"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"interval"						"3"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_crit_chance"		"25"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"item_magical_crit_damage"		"150"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"150"
			}
		}
	}
	"item_last_prism"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/artifact/item_last_prism"
		"AbilityTextureName"					"item_seer_stone"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_ARTIFACT"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"AbilityUnitTargetTeam"					"DOTA_UNIT_TARGET_TEAM_ENEMY"
		"AbilityUnitTargetType"					"DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
		"CrystalCost"							"20000"
		"ItemSellable"							"1"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_all_stats"				"800"
			}
			"02"
			{
				"var_type"						"FIELD_INTEGER"
				"item_cooldown_reduction"		"20"
			}
			"03"
			{
				"var_type"						"FIELD_INTEGER"
				"item_mana_regen_pct"			"10"
			}
			"04"
			{
				"var_type"						"FIELD_INTEGER"
				"damage"						"0"
				"_primary"						"20"
			}
			"05"
			{
				"var_type"						"FIELD_INTEGER"
				"radius"						"900"
			}
			"06"
			{
				"var_type"						"FIELD_INTEGER"
				"damage_bonus"					"15"
			}
			"07"
			{
				"var_type"						"FIELD_INTEGER"
				"duration"						"3"
			}
		}
	}
	"item_shipin_2_1"
	{
		"BaseClass"								"item_datadriven"
		"AbilityTextureName"					"item_gloves"
		"ItemQuality"							"component"
		"ItemShareability"						"ITEM_FULLY_SHAREABLE"
		"ItemDisassembleRule"					"DOTA_ITEM_DISASSEMBLE_NEVER"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_PASSIVE"
		"ItemCost"								"500"
		"AbilitySpecial"
		{
			"01"
			{
				"var_type"						"FIELD_INTEGER"
				"item_attack_speed"				"20"
			}
		}
	}
	"item_enchant"
	{
		"BaseClass"								"item_lua"
		"ScriptFile"							"abilities/items/consumable/item_enchant"
		"AbilityTextureName"					"item_titan_power"
		"CustomItemType"						"CUSTOM_ITEM_TYPE_CONSUMABLE"
		"AbilityBehavior"						"DOTA_ABILITY_BEHAVIOR_IMMEDIATE | DOTA_ABILITY_BEHAVIOR_NO_TARGET"
		"ItemSellable"							"0"
		"ItemKillable"							"0"
		"ItemPurchasable"						"0"
	}
}
