vec3_zero = Vector(0, 0, 0)

AI_THINK_TICK_TIME = 0.5	-- AI间隔

----------------------------------------物品类型----------------------------------------
CUSTOM_ITEM_TYPE_EQUIPMENT = 0		---装备
CUSTOM_ITEM_TYPE_ABILITY_BOOK = 1	---技能书
CUSTOM_ITEM_TYPE_DEVOUR = 2			---神佑宝石
CUSTOM_ITEM_TYPE_HERCULES = 3		---海格力斯
CUSTOM_ITEM_TYPE_DIVINE = 4			---法宝
CUSTOM_ITEM_TYPE_SPECIAL_DIVINE = 5	---特殊法宝
CUSTOM_ITEM_TYPE_BASE = 6			---基地相关
CUSTOM_ITEM_TYPE_CHEST = 7			---宝箱
CUSTOM_ITEM_TYPE_CASTING = 8		---铸造
CUSTOM_ITEM_TYPE_TREAUSURE_MAP = 9	---藏宝图
CUSTOM_ITEM_TYPE_OTHER = 10			---其他

CUSTOM_ITEM_TYPE_CONSUMABLE = 11			---消耗品
CUSTOM_ITEM_TYPE_ATTRIBUTE_BOOK = 12		---消耗品
CUSTOM_ITEM_TYPE_MAIN_WEAPON = 13			---武器
CUSTOM_ITEM_TYPE_ARMOR = 14					---护甲
CUSTOM_ITEM_TYPE_DEPUTY = 15				---副手
CUSTOM_ITEM_TYPE_ENCHANT = 16				---附魔卷轴
CUSTOM_ITEM_TYPE_ARTIFACT = 17				---神器

----------------------------------------资源类型----------------------------------------
CUSTOM_RESOURCE_TYPE_GOLD = 0		---金币
CUSTOM_RESOURCE_TYPE_CRYSTAL = 1	---荣誉值
CUSTOM_RESOURCE_TYPE_SCORE = 2		---历练值
CUSTOM_RESOURCE_TYPE_EXP = 3		---经验
CUSTOM_RESOURCE_TYPE_GOLD_GAIN = 4	---金币获取

----------------------------------------技能类型----------------------------------------
CUSTOM_ABILITY_TYPE_HERO = 0		---英雄自带技能
CUSTOM_ABILITY_TYPE_TALENT = 1		---天赋

----------------------------------------物品栏事件类型----------------------------------------
CUSTOM_INVENTORY_CHANGE_SWITCH = 0	---交换位置
CUSTOM_INVENTORY_CHANGE_LOSE = 1	---丢下
CUSTOM_INVENTORY_CHANGE_RECEIVE = 2	---得到

----------------------------------------任务类型----------------------------------------
TASK_TAG_REPEAT = 0					--- 重复
TASK_TAG_CANT_ABANDONED = 1			--- 不可放弃的
TASK_TAG_AUTO_COMPLETE = 2			--- 自动完成
TASK_TAG_HIDE = 3					--- 隐藏任务
TASK_TAG_RANDOM = 4					--- 随机任务

----------------------------------------任务需求----------------------------------------
TASK_STAGE_TYPE_KILL = 0			--- 击杀
TASK_STAGE_TYPE_ITEM = 1			--- 物品
TASK_STAGE_TYPE_TALK = 2			--- 对话

----------------------------------------任务奖励----------------------------------------
TASK_REWARD_TYPE_ATTRIBUTE = 0			--- 属性
TASK_REWARD_TYPE_ITEM = 1				--- 物品
TASK_REWARD_TYPE_RESOURCE = 2			--- 资源
TASK_REWARD_TYPE_SCEPTER = 3			--- 专属装备
TASK_REWARD_TYPE_REBORN = 4				--- 转生
TASK_REWARD_TYPE_MODIFIER = 5			--- buff

----------------------------------------任务解锁要求----------------------------------------
TASK_UNLOCK_TYPE_TASK = 0			--- 任务解锁
TASK_UNLOCK_TYPE_ITEM = 1			--- 物品解锁
TASK_UNLOCK_TYPE_KILL = 2			--- 击杀解锁

----------------------------------------任务状态----------------------------------------
TASK_STATE_TYPE_NONE = 0			--- 没有接取
TASK_STATE_TYPE_PROGRESS = 1		--- 执行中
TASK_STATE_TYPE_FINISH = 2			--- 完成
TASK_STATE_TYPE_RECEIVED = 3		--- 完成并领取奖励
TASK_STATE_TYPE_LOCK = 4			--- 未解锁

----------------------------------------可提升属性----------------------------------------
CUSTOM_ATTRIBUTE_ATTACK = "CUSTOM_ATTRIBUTE_ATTACK"								---攻击
CUSTOM_ATTRIBUTE_ATTACK_SPEED = "CUSTOM_ATTRIBUTE_ATTACK_SPEED"					---攻击速度
CUSTOM_ATTRIBUTE_ATTACK_RANGE = "CUSTOM_ATTRIBUTE_ATTACK_RANGE"					---攻击距离
CUSTOM_ATTRIBUTE_ATTACK_REDUCE_ARMOR = "CUSTOM_ATTRIBUTE_ATTACK_REDUCE_ARMOR"	---攻击减甲
CUSTOM_ATTRIBUTE_CLEAVE_DAMAGE = "CUSTOM_ATTRIBUTE_CLEAVE_DAMAGE"				---分裂伤害
CUSTOM_ATTRIBUTE_ARMOR_IGNORE = "CUSTOM_ATTRIBUTE_ARMOR_IGNORE"					---无视护甲

CUSTOM_ATTRIBUTE_STRENGTH = "CUSTOM_ATTRIBUTE_STRENGTH"							---力量
CUSTOM_ATTRIBUTE_AGILITY = "CUSTOM_ATTRIBUTE_AGILITY"							---敏捷
CUSTOM_ATTRIBUTE_INTELLECT = "CUSTOM_ATTRIBUTE_INTELLECT"						---智力
CUSTOM_ATTRIBUTE_STRENGTH_GAIN = "CUSTOM_ATTRIBUTE_STRENGTH_GAIN"				---力量成长
CUSTOM_ATTRIBUTE_AGILITY_GAIN = "CUSTOM_ATTRIBUTE_AGILITY_GAIN"					---敏捷成长
CUSTOM_ATTRIBUTE_INTELLECT_GAIN = "CUSTOM_ATTRIBUTE_INTELLECT_GAIN"				---智力成长
CUSTOM_ATTRIBUTE_ALL = "CUSTOM_ATTRIBUTE_ALL"									---全属性

CUSTOM_ATTRIBUTE_HEALTH = "CUSTOM_ATTRIBUTE_HEALTH"								---生命
CUSTOM_ATTRIBUTE_HEALTH_REGEN = "CUSTOM_ATTRIBUTE_HEALTH_REGEN"					---生命回复
CUSTOM_ATTRIBUTE_MANA = "CUSTOM_ATTRIBUTE_MANA"									---魔法
CUSTOM_ATTRIBUTE_MANA_REGEN = "CUSTOM_ATTRIBUTE_MANA_REGEN"						---魔法回复
CUSTOM_ATTRIBUTE_ARMOR = "CUSTOM_ATTRIBUTE_ARMOR"								---护甲
CUSTOM_ATTRIBUTE_EVASION = "CUSTOM_ATTRIBUTE_EVASION"							---闪避
CUSTOM_ATTRIBUTE_COOLDOWN_REDUCE = "CUSTOM_ATTRIBUTE_COOLDOWN_REDUCE"			---冷却缩减
CUSTOM_ATTRIBUTE_DAMAGE_IGNORE = "CUSTOM_ATTRIBUTE_DAMAGE_IGNORE"				---伤害格挡
CUSTOM_ATTRIBUTE_ALL_LIFESTEAL = "CUSTOM_ATTRIBUTE_ALL_LIFESTEAL"				---全能吸血
CUSTOM_ATTRIBUTE_DAMAGE_REDUCE = "CUSTOM_ATTRIBUTE_DAMAGE_REDUCE"				---伤害减免
CUSTOM_ATTRIBUTE_DAMAGE_REDUCE2 = "CUSTOM_ATTRIBUTE_DAMAGE_REDUCE2"				---伤害再减免

CUSTOM_ATTRIBUTE_PHYSICAL_DAMAGE = "CUSTOM_ATTRIBUTE_PHYSICAL_DAMAGE"			---物理伤害
CUSTOM_ATTRIBUTE_MAGICAL_DAMAGE = "CUSTOM_ATTRIBUTE_MAGICAL_DAMAGE"				---魔法伤害
CUSTOM_ATTRIBUTE_FINALLY_DAMAGE = "CUSTOM_ATTRIBUTE_FINALLY_DAMAGE"				---最终伤害
CUSTOM_ATTRIBUTE_PHYSICAL_CRIT_CHANCE = "CUSTOM_ATTRIBUTE_PHYSICAL_CRIT_CHANCE"	---物理暴击概率
CUSTOM_ATTRIBUTE_PHYSICAL_CRIT_DAMAGE = "CUSTOM_ATTRIBUTE_PHYSICAL_CRIT_DAMAGE"	---物理暴击伤害
CUSTOM_ATTRIBUTE_MAGICAL_CRIT_CHANCE = "CUSTOM_ATTRIBUTE_MAGICAL_CRIT_CHANCE"	---魔法暴击概率
CUSTOM_ATTRIBUTE_MAGICAL_CRIT_DAMAGE = "CUSTOM_ATTRIBUTE_MAGICAL_CRIT_DAMAGE"	---魔法暴击伤害

CUSTOM_ATTRIBUTE_DROP_CHANCE = "CUSTOM_ATTRIBUTE_DROP_CHANCE"					---掉宝
CUSTOM_ATTRIBUTE_KILL_SCORE = "CUSTOM_ATTRIBUTE_KILL_SCORE"						---杀敌
CUSTOM_ATTRIBUTE_KILL_GOLD = "CUSTOM_ATTRIBUTE_KILL_GOLD"						---资源
CUSTOM_ATTRIBUTE_EXPERIENCE = "CUSTOM_ATTRIBUTE_EXPERIENCE"						---经验

CUSTOM_ATTRIBUTE_ATTACK_PER_SEC = "CUSTOM_ATTRIBUTE_ATTACK_PER_SEC"				---每秒攻击
CUSTOM_ATTRIBUTE_HEALTH_PER_SEC = "CUSTOM_ATTRIBUTE_HEALTH_PER_SEC"				---每秒生命
CUSTOM_ATTRIBUTE_ARMOR_PER_SEC = "CUSTOM_ATTRIBUTE_ARMOR_PER_SEC"				---每秒护甲
CUSTOM_ATTRIBUTE_ALL_PER_SEC = "CUSTOM_ATTRIBUTE_ALL_PER_SEC"					---每秒全属性
CUSTOM_ATTRIBUTE_STRENGTH_PER_SEC = "CUSTOM_ATTRIBUTE_STRENGTH_PER_SEC"			---每秒力量
CUSTOM_ATTRIBUTE_AGILITY_PER_SEC = "CUSTOM_ATTRIBUTE_AGILITY_PER_SEC"			---每秒敏捷
CUSTOM_ATTRIBUTE_INTELLECT_PER_SEC = "CUSTOM_ATTRIBUTE_INTELLECT_PER_SEC"		---每秒智力
CUSTOM_ATTRIBUTE_GOLD_PER_SEC = "CUSTOM_ATTRIBUTE_GOLD_PER_SEC"					---每秒金币

CUSTOM_ATTRIBUTE_PHYSICAL_DAMAGE_PER_MIN = "CUSTOM_ATTRIBUTE_PHYSICAL_DAMAGE_PER_MIN"			---每分钟物理伤害
CUSTOM_ATTRIBUTE_MAGICAL_DAMAGE_PER_MIN = "CUSTOM_ATTRIBUTE_MAGICAL_DAMAGE_PER_MIN"				---每分钟魔法伤害
CUSTOM_ATTRIBUTE_ATTACK_PER_MIN = "CUSTOM_ATTRIBUTE_ATTACK_PER_MIN"				---每分钟攻击
CUSTOM_ATTRIBUTE_HEALTH_PER_MIN = "CUSTOM_ATTRIBUTE_HEALTH_PER_MIN"				---每分钟生命
CUSTOM_ATTRIBUTE_ARMOR_PER_MIN = "CUSTOM_ATTRIBUTE_ARMOR_PER_MIN"				---每分钟护甲
CUSTOM_ATTRIBUTE_ALL_PER_MIN = "CUSTOM_ATTRIBUTE_ALL_PER_MIN"					---每分钟全属性
CUSTOM_ATTRIBUTE_STRENGTH_PER_MIN = "CUSTOM_ATTRIBUTE_STRENGTH_PER_MIN"			---每分钟力量
CUSTOM_ATTRIBUTE_AGILITY_PER_MIN = "CUSTOM_ATTRIBUTE_AGILITY_PER_MIN"			---每分钟敏捷
CUSTOM_ATTRIBUTE_INTELLECT_PER_MIN = "CUSTOM_ATTRIBUTE_INTELLECT_PER_MIN"		---每分钟智力

CUSTOM_ATTRIBUTE_ATTACK_ATTACK = "CUSTOM_ATTRIBUTE_ATTACK_ATTACK"				---攻击攻击
CUSTOM_ATTRIBUTE_ATTACK_HEALTH = "CUSTOM_ATTRIBUTE_ATTACK_HEALTH"				---攻击生命
CUSTOM_ATTRIBUTE_ATTACK_ARMOR = "CUSTOM_ATTRIBUTE_ATTACK_ARMOR"					---攻击护甲
CUSTOM_ATTRIBUTE_ATTACK_ALL = "CUSTOM_ATTRIBUTE_ATTACK_ALL"						---攻击全属性
CUSTOM_ATTRIBUTE_ATTACK_STRENGTH = "CUSTOM_ATTRIBUTE_ATTACK_STRENGTH"			---攻击力量
CUSTOM_ATTRIBUTE_ATTACK_AGILITY = "CUSTOM_ATTRIBUTE_ATTACK_AGILITY"				---攻击敏捷
CUSTOM_ATTRIBUTE_ATTACK_INTELLECT = "CUSTOM_ATTRIBUTE_ATTACK_INTELLECT"			---攻击智力

CUSTOM_ATTRIBUTE_KILL_ATTACK = "CUSTOM_ATTRIBUTE_KILL_ATTACK"					---击杀攻击
CUSTOM_ATTRIBUTE_KILL_HEALTH = "CUSTOM_ATTRIBUTE_KILL_HEALTH"					---击杀生命
CUSTOM_ATTRIBUTE_KILL_ARMOR = "CUSTOM_ATTRIBUTE_KILL_ARMOR"						---击杀护甲
CUSTOM_ATTRIBUTE_KILL_ALL = "CUSTOM_ATTRIBUTE_KILL_ALL"							---击杀全属性
CUSTOM_ATTRIBUTE_KILL_STRENGTH = "CUSTOM_ATTRIBUTE_KILL_STRENGTH"				---击杀力量
CUSTOM_ATTRIBUTE_KILL_AGILITY = "CUSTOM_ATTRIBUTE_KILL_AGILITY"					---击杀敏捷
CUSTOM_ATTRIBUTE_KILL_INTELLECT = "CUSTOM_ATTRIBUTE_KILL_INTELLECT"				---击杀智力


CUSTOM_ATTRIBUTE_RESPAWN_TIME = "CUSTOM_ATTRIBUTE_RESPAWN_TIME"					---复活时间(降低)